title: Yibo Wang's personal page
page-top-title: Sen Li
top-section-bg-text: Electrical Engineering
home-subtitle: Sen Li&ensp;|&ensp;王艺博copyright-text: '&copy; Yibo Wang 2023-2024. All Rights Reserved.'
